
build:
    image: docker.km3net.de/base/nmh:dev
    stage: build
    variables:
        OSCPROBDIR: /OscProb
    script:
        - source /opt/root-6.14.06/bin/thisroot.sh
        - source /Jpp/setenv.sh /Jpp
        - source setenv.sh
        - make -j4
        - doxygen doxyconf
        - cp doxygen/html/ public/
    artifacts:
        paths:
           - common_software
           - fitter_software
           - apps/*
           - public
    cache:
        key: $CI_COMMIT_REF_SLUG
        untracked: true

test:
    image: docker.km3net.de/base/nmh:dev
    stage: test
    variables:
        OSCPROBDIR: /OscProb
    script:
        - source /opt/root-6.14.06/bin/thisroot.sh
        - source /Jpp/setenv.sh /Jpp
        - source setenv.sh
        - make test
    artifacts:
      reports:
        junit: "junit.xml"
    dependencies:
        - build
