image: docker.km3net.de/base/nmh:dev

build:
    script:
        - source /opt/root-6.14.06/bin/thisroot.sh
        - source /Jpp/setenv.sh /Jpp
        - make
    cache:
        key: $CI_COMMIT_REF_SLUG
        untracked: true