
build:
    image: docker.km3net.de/base/nmh:dev
    stage: build
    variables:
        OSCPROBDIR: /OscProb
    script:
        - source /opt/root-6.14.06/bin/thisroot.sh
        - source /Jpp/setenv.sh /Jpp
        - source setenv.sh
        - make -j4
    cache:
        key: $CI_COMMIT_REF_SLUG
        untracked: true

test:
    image: docker.km3net.de/base/nmh:dev
    stage: test
    script:
        - make test
    artifacts:
      reports:
        junit: "junit.xml"
    dependencies:
	- build
