
pages:
    image: docker.km3net.de/base/nmh:dev
    stage: deploy
    variables:
        OSCPROBDIR: /OscProb
    script:
        - source /opt/root-6.14.06/bin/thisroot.sh
        - source /Jpp/setenv.sh /Jpp
        - source setenv.sh
        - doxygen doxyconf
        - cp -r doxygen/html/ public/
    artifacts:
        paths:
           - public