
#include "EffMass.h"
#include "NMHUtils.h"
#include "FileHeader.h"

#include "JTools/JRange.hh"
#include "Jeep/JParser.hh"
#include "Jeep/JMessage.hh"

#include "TMath.h"
#include "TFile.h"
#include "TMultiGraph.h"

#include <stdexcept>

using namespace JTOOLS;

/** Namespace that holds functions and variables for the `DataQuality` application. */
namespace DATAQUALITY {

  /** Function to issue a system command and check for return.
      \param syscmd   System command
   */
  void SystemCmd( TString syscmd ) {
    Int_t sysret = system(syscmd);
    if (sysret != 0) {
      cout << "NOTICE DATAQUALITY::SysretOK() returned " << sysret << " for cmd " << syscmd << endl;
    }
  }

  /** Function to extract the run number from the filename 
      \param fname file name
      \return      file number
   */
  Int_t GetRunNr(TString fname) {
    Int_t start = fname.Index("GeV_") + 4;
    Int_t stop  = fname.Index(".root");
    TString fnr = fname( start, stop-start );
    return std::stoi( (string)fnr );
  }

  /** Structure that holds the graphs with run nr vs nr of events*/
  struct Graphs {

    TString name;
    TGraph g_gen_nu, g_gen_nub, g_sel_nu, g_sel_nub;
    vector<TGraph*> graphs;
    
    Graphs(TString _name) {

      name = _name;

      g_gen_nu  = TGraph();
      g_gen_nub = TGraph();
      g_sel_nu  = TGraph();
      g_sel_nub = TGraph();

      g_gen_nu .SetNameTitle("gen_nu_" + name , "gen_nu_" + name);
      g_gen_nub.SetNameTitle("gen_nub_" + name, "gen_nub_" + name);
      g_sel_nu .SetNameTitle("sel_nu_" + name , "sel_nu_" + name);
      g_sel_nub.SetNameTitle("sel_nub_" + name, "sel_nub_" + name);

      graphs = { &g_gen_nu, &g_gen_nub, &g_sel_nu, &g_sel_nub };

      for (auto g: graphs) {

	g->GetXaxis()->SetTitle("run number");
	g->GetYaxis()->SetTitle("nr of events");
	
	if ( ((TString)g->GetName()).Contains("gen") ) {
	  g->SetMarkerStyle(20);
	  g->SetMarkerColor(kBlue);
	}
	else {
	  g->SetMarkerStyle(21);
	  g->SetMarkerColor(kRed);
	}
	
      } //end loop over graphs
      
    } // end constructor
    
  }; // end struct Graph
  
};

/** This application creates data quality plots on the output files generated by `EffMhists` application */
int main(const int argc, const char **argv) {

  using namespace DATAQUALITY;

  //------------------------------------------------------
  //parse command line arguments
  //------------------------------------------------------  
  TString     input_dir;
  TString     output_file;
  JRange<int> E_range_low;
  JRange<int> E_range_high;

  try {

    JParser<> zap("This application creates data quality plots on the output files generated by `EffMhists` application");

    zap['i'] = make_field(input_dir      , "Directory with EffMhists outputs");
    zap['o'] = make_field(output_file    , "Name with data quality output plots") = "dataquality.root";
    zap['d'] = make_field(E_range_low    , "Low energy range of the MC production") = JRange<int>(1,5);
    zap['u'] = make_field(E_range_high   , "High energy range of the MC production") = JRange<int>(3,100);

    if ( zap.read(argc, argv) != 0 ) return 1;
  }
  catch(const exception &error) {
    FATAL(error.what() << endl);
  }

  //------------------------------------------------------
  // create strings to search 
  //------------------------------------------------------  
  std::vector<TString> flavors = { "elec" , "muon" , "tau" };
  std::vector<TString> ints    = { "NC", "CC" };
  std::vector<TString> eranges;
  eranges.push_back( to_string( E_range_low.getLowerLimit() ) + "-" + to_string( E_range_low.getUpperLimit() ) );
  eranges.push_back( to_string( E_range_high.getLowerLimit() ) + "-" + to_string( E_range_high.getUpperLimit() ) );

  vector< std::pair<TString, TString> > searchstr;

  for (auto f: flavors) {
    for (auto i: ints) {
      for (auto r: eranges) {
	TString str = input_dir + "/*" + f + "*" + i + "*" + r + "*"; // search string
	TString nstr = f + "_" + i + "_" + r;                         // name string for ROOT graphs
	searchstr.push_back( std::make_pair(str, nstr) );
      }
    }
  }

  //------------------------------------------------------
  // look up the files for each search string
  //------------------------------------------------------  
  std::map<TString, vector<TString> > str_vec_pairs;

  for (auto p: searchstr) {

    TString syscmd;

    TString tmpfile = "tmp.txt";
    syscmd = "ls " + p.first + " > " + tmpfile;
    SystemCmd ( syscmd );
    vector<TString> filelines = NMHUtils::ReadLines(tmpfile);
    SystemCmd ( "rm " + tmpfile );

    if (filelines.size() == 0) {
      cout << "NOTICE DataQuality() no files for selection " << p.first << endl;
      continue;
    }
    else {
      cout << "NOTICE DataQuality() " << filelines.size() << " files for selection " << p.first << endl;
    }

    str_vec_pairs.insert( std::make_pair(p.second, filelines) );

  }

  //------------------------------------------------------
  // loop over the files, get the number of generated and selected events
  //------------------------------------------------------
  vector<Graphs> G;

  for (auto kv: str_vec_pairs) {

    Graphs gr( kv.first );
    
    for (auto fname: kv.second) {
      
      Int_t runnr = GetRunNr( fname );

      TFile fin( fname, "READ");
      if ( !fin.IsOpen() ) {
	throw std::invalid_argument("ERROR! DataQuality() cannot open file " + (string)fname);
      }

      TH3D* hgen_nu  = (TH3D*)fin.Get("Generated_nu");
      TH3D* hgen_nub = (TH3D*)fin.Get("Generated_nub");
      TH3D* hsel_nu  = (TH3D*)fin.Get("Selected_nu");
      TH3D* hsel_nub = (TH3D*)fin.Get("Selected_nub");
      
      gr.g_gen_nu .SetPoint( gr.g_gen_nu .GetN(), runnr, hgen_nu ->GetEntries() );
      gr.g_gen_nub.SetPoint( gr.g_gen_nub.GetN(), runnr, hgen_nub->GetEntries() );
      gr.g_sel_nu .SetPoint( gr.g_sel_nu .GetN(), runnr, hsel_nu ->GetEntries() );
      gr.g_sel_nub.SetPoint( gr.g_sel_nub.GetN(), runnr, hsel_nub->GetEntries() );
      
    }

    G.push_back( gr );

  }

  //------------------------------------------------------
  // create some plots and write to file
  //------------------------------------------------------
  
  TFile fout(output_file, "RECREATE");

  for (auto gr: G) {

    // sort the graphs in X value
    gr.g_gen_nu.Sort();
    gr.g_sel_nu.Sort();
    gr.g_gen_nub.Sort();
    gr.g_sel_nub.Sort();

    // check that the same number of runs exist for generated and selected
    if ( gr.g_gen_nu.GetN() != gr.g_sel_nu.GetN() ) {
      throw std::logic_error("ERROR! DataQuality() generated and selected nu events have different number of files. Investigate the MC production");
    }

    if ( gr.g_gen_nub.GetN() != gr.g_sel_nub.GetN() ) {
      throw std::logic_error("ERROR! DataQuality() generated and selected nubar events have different number of files. Investigate the DataQuality.C code and the MC production");
    }
    
    // loop over the points and calculate the ratio
    TGraph ratio_nu, ratio_nub;
    ratio_nu .SetNameTitle( gr.name + "ratio_nu" , gr.name + "ratio_nu"  );
    ratio_nub.SetNameTitle( gr.name + "ratio_nub", gr.name + "ratio_nub" );

    Double_t xg,yg, xs, ys;

    // --------------------- for nu ------------------------------------------
    for (Int_t i = 0; i < gr.g_gen_nu.GetN(); i++) {

      gr.g_gen_nu.GetPoint(i, xg, yg);
      gr.g_sel_nu.GetPoint(i, xs, ys);

      if ( xs != xg ) {
	throw std::logic_error("ERROR! DataQuality() different run numbers on the x-axis for nu events. Investigate the DataQuality.C code and the MC production");
      }

      ratio_nu.SetPoint( i, xs, ys/yg );
      
    }

    // --------------------- for nub ------------------------------------------
    for (Int_t i = 0; i < gr.g_gen_nub.GetN(); i++) {

      gr.g_gen_nub.GetPoint(i, xg, yg);
      gr.g_sel_nub.GetPoint(i, xs, ys);

      if ( xs != xg ) {
	throw std::logic_error("ERROR! DataQuality() different run numbers on the x-axis for nubar events. Investigate the DataQuality.C code and the MC production");
      }

      ratio_nub.SetPoint( i, xs, ys/yg );
      
    }

    ratio_nu.SetLineColor(kRed);
    ratio_nu.SetLineWidth(2);
    ratio_nub.SetLineColor(kRed);
    ratio_nub.SetLineWidth(2);

    ratio_nu.Write();
    ratio_nub.Write();
    
    // create multigraphs that show all the graphs
    TMultiGraph mg_nu, mg_nub;
    
    mg_nu.Add( &gr.g_gen_nu );
    mg_nu.Add( &gr.g_sel_nu );

    mg_nub.Add( &gr.g_gen_nub );
    mg_nub.Add( &gr.g_sel_nub );
    
    mg_nu.Write( gr.name + "_nu" );
    mg_nub.Write( gr.name + "_nub" );
    
  }

  fout.Close();
  
}
